### PR TITLE
Drop all eos-link-* that are not webapps

### PR DESCRIPTION
**Pull request by andrunko**
We don't ship any of these links in the default grid layouts of our current personalities but the Shell still has to parse them (only to hide them afterwards), so let's remove them.

https://phabricator.endlessm.com/T30891
https://phabricator.endlessm.com/T4377

### CODE REVIEW

**Comment by pwithnall** [comment]
This looks good to me. I grepped my checkouts of notable parts of the Endless source (`cd checkouts; ack --ignore-dir eos-shell-content eos-link | sort -u`), and only found the following uses of `eos-link` which need to be updated in [eos-qa-tools](https://github.com/endlessm/eos-qa-tools/blob/master/media-stick-stress/config) — it’s using `eos-link-teleton`, `eos-link-universidadrural`, `eos-link-clarovideo` and `eos-link-bbc` which are deleted by this PR.

The other results I found are below, for reference. None of them are deleted by this PR, which is OK.
```
eos-image-builder/data/icon-grid/africa_east/icon-grid-C.json:18:    "eos-link-facebook.desktop",
eos-image-builder/data/icon-grid/africa_east/icon-grid-C.json:19:    "eos-link-youtube.desktop",
eos-image-builder/data/icon-grid/africa_east/icon-grid-C.json:20:    "eos-link-whatsapp.desktop",
eos-image-builder/data/icon-grid/africa_east/icon-grid-C.json:57:    "eos-link-twitter.desktop",
eos-image-builder/data/icon-grid/africa_east/icon-grid-C.json:60:    "eos-link-gmail.desktop"
eos-image-builder/data/icon-grid/campeche/icon-grid-C.json:21:    "eos-link-duolingo.desktop",
eos-image-builder/data/icon-grid/honduras/student/icon-grid-C.json:9:    "eos-link-virtualschool.desktop",
eos-image-builder/data/icon-grid/tamaulipas/icon-grid-C.json:4:    "eos-link-tamaulipasform.desktop",
eos-image-builder/data/icon-grid/tamaulipas/icon-grid-C.json:5:    "eos-link-telegram.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:29:    "eos-link-commonlit.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:30:    "eos-link-getepic.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:31:    "eos-link-myon.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:32:    "eos-link-raz-kids.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:33:    "eos-link-tickettoread.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:34:    "eos-link-audible.desktop"
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:37:    "eos-link-vmathlive.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:38:    "eos-link-imaginelearning-math.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:39:    "eos-link-desmos-teacher.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:40:    "eos-link-bigideasmath.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:44:    "eos-link-google-classroom.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:45:    "eos-link-clever.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:46:    "eos-link-playposit.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:47:    "eos-link-edcite.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:48:    "eos-link-edpuzzle.desktop",
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:64:    "eos-link-duolingo-tinycards.desktop"
eos-image-builder/data/icon-grid/tfa/icon-grid-C.json:67:    "eos-link-abcya.desktop",
```

**Comment by wjt** [comment]
The default icon grids are specified in eos-shell-content. The ones in the image builder are overrides

**Comment by wjt** [comment]
```
wjt@camille:~/src/endlessm/eos-shell-content$ find -name '*.json.in' | xargs grep eos-link | perl -lane 'm{"(.*)"} and print $1' | sort | uniq                                                                                                                                                                                                                             
eos-link-baidudict.desktop
eos-link-bingdict.desktop
eos-link-duolingo.desktop
eos-link-facebook.desktop
eos-link-gmail.desktop
eos-link-qq.desktop
eos-link-twitter.desktop
eos-link-wechat.desktop
eos-link-whatsapp.desktop
eos-link-youtube.desktop
```

**Comment by wjt** [comment]
Those are all here too!

**Pull request merged**
