### PR TITLE
Remove Telegram link

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
https://phabricator.endlessm.com/T31011

### CODE REVIEW

**Review by andrunko — CHANGES_REQUESTED** [review]
There is a mention of telegram on `eos-app-store-link-content.gresource.xml` (unsure where this is used) and also `telegram.jpg` that we should remove here.

**Comment by GeorgesStavracas** [comment]
These files are generated...

**Comment by andrunko** [comment]
> These files are generated...

Right, the `eos-app-store-link-content.gresource.xml` is indeed autogen but not `telegram.jpg` which I see you removed on the latest changes.

**Review by andrunko — APPROVED** [review]

**Comment by andrunko** [comment]
> > These files are generated...
> 
> Right, the `eos-app-store-link-content.gresource.xml` is indeed autogen but not `telegram.jpg` which I see you removed on the latest changes.

@GeorgesStavracas Actually I misread the changes and confused `telegram.png` with `telegram.jpg` - could you please check and remove `telegram.jpg` as well? (feel free to push directly to master if only this change).

**Pull request merged**
