### PR TITLE
Update gnome-control-center screenshots

### PR DESCRIPTION
**Pull request by uajain**
https://phabricator.endlessm.com/T27552

Let's show the new cool stuff. :100:

### CODE REVIEW

**Comment by uajain** [comment]
> Shouldn't we also either update or delete the `pt` and `es` screenshots?
> 
Addressed. Deleted `pt` and `es` and their references on content.json. 

> It would be nice to submit some screenshots [upstream](https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/shell/appdata/gnome-control-center.appdata.xml.in).

Yeah need to find some time and energy. The screenshots need to be from upstream branch gnome-3-34 as due to the string change "App center" in these particular screenshots I posted here.

**Comment by uajain** [comment]
Looks like the magic is **not** still working! 
Screenshot from 2019-09-30 17-24-59


The cache still fetches the old screenshots of control-center :man_shrugging: 
```
uajain@endless:~$ ls -al .cache/gnome-software/screenshots/624x351/
total 216
drwxr-xr-x 2 uajain uajain  4096 Sep 30 17:22 .
drwxr-xr-x 5 uajain uajain  4096 Sep 30 17:21 ..
-rw-r--r-- 1 uajain uajain 48496 Sep 30 17:22 5688f6aeb98722fbc8f018c2d0106e3c966c10ad759b0ca4fb1c9b7fda84a09f-gnome-control-center-screenshot3.jpg
-rw-r--r-- 1 uajain uajain 82263 Sep 30 17:22 775e86f7f304b342f475ecea0d220f9ebb81be798755a1384b21885922641e58-gnome-control-center-screenshot2.jpg
-rw-r--r-- 1 uajain uajain 75254 Sep 30 17:22 cfbc4e62d41d4df31449ca6e5a7ab03100b0be25cba02764380bd4b6527fb216-gnome-control-center-screenshot1.jpg
```

**Comment by wjt** [comment]
@uajain let's open a Phabricator ticket to track this. My guess would be that there is nothing that actually publishes these screenshots (any more). One path forward would be to replace this with an entry in gnome-software-data, arrange for the existing job that publishes that to also publish screenshots from that repo, and remove the eos-shell-content goop from gnome-control-center. See https://phabricator.endlessm.com/T27085.

**Comment by dbnicholson** [comment]
The population of the screenshots directory in gnome-software-data happens from eos-build, but only when building flatpaks on jenkins.

https://github.com/endlessm/eos-build/blob/master/bundle_scripts/flatpak-export-assets.py
https://github.com/endlessm/gnome-software-data/commits/master/screenshots

I honestly wasn't involved in that part of the development, so I don't much know anymore if/how that works.

**Comment by dbnicholson** [comment]
Wrong directory for the screenshots in gnome-software-data that actually goes on s3. It's https://github.com/endlessm/gnome-software-data/commits/master/s3/screenshots. I don't know why there are 2 screenshots directories there.

**Pull request merged**
