### PR TITLE
Remove China-specific links

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
https://phabricator.endlessm.com/T31011

### CODE REVIEW

**Review by andrunko — CHANGES_REQUESTED** [review]
Looks like there are more files that need to be deleted here. To name a few:
- eos-link-wechat.png
- baidueducation*, baiduencyclopedia*, baidunews* (also needs to be removed from the `.json` files)
- qq*
- While on that it would also be good to remove a leftover from telegram as mentioned on https://github.com/endlessm/eos-shell-content/pull/236#issuecomment-720639868

More generally any image/file that refers to these apps we are removing can go away as well.

**Comment by GeorgesStavracas** [comment]
> baidueducation*, baiduencyclopedia*, baidunews* (also needs to be removed from the .json files)

These don't have link icons added by default.

> While on that it would also be good to remove a leftover from telegram as mentioned on #236 (comment)

I've pushed a commit for that 2 weeks ago, it's in master

**Comment by andrunko** [comment]
> > baidueducation*, baiduencyclopedia*, baidunews* (also needs to be removed from the .json files)
> 
> These don't have link icons added by default.
> 

hmm, I see this is a leftover from https://github.com/endlessm/eos-shell-content/pull/235 where we removed all links that are not webapps. I would probably remove them here also as related but not a blocker.

> > While on that it would also be good to remove a leftover from telegram as mentioned on #236 (comment)
> 
> I've pushed a commit for that 2 weeks ago, it's in master

Great, missed this one.

**Comment by andrunko** [comment]
Looks like there are still some leftovers, namely eos-link-*.png for the apps getting removed here (e.g. eos-link-baidudict.png, eos-link-kugomusic.png, etc).

**Comment by GeorgesStavracas** [comment]
Seems like I forgot every icon except for the first commit. Should be fixed now.

> I would probably remove them here also as related but not a blocker.

I don't see a reason to do this here, if necessary we can open a ticket and track it separately.

**Review by andrunko — APPROVED** [review]

**Comment by andrunko** [comment]
> > I would probably remove them here also as related but not a blocker.
> 
> I don't see a reason to do this here, if necessary we can open a ticket and track it separately.

Fair enough.

**Pull request merged**
